### ISSUE TITLE
`TPM_RC_LOCKOUT` received during kselftest-tpm2

### ISSUE THREAD

**Issue by nfraprado** [kernelci/kernelci-project#101]
Issue found in https://github.com/kernelci/kernelci-core/pull/1025.

The following tests from kselftest-tpm2
```
test_seal_with_auth (tpm2_tests.SmokeTest)
test_seal_with_policy (tpm2_tests.SmokeTest)
test_unseal_with_wrong_auth (tpm2_tests.SmokeTest)
test_unseal_with_wrong_policy (tpm2_tests.SmokeTest)
```

fail with

```
# ======================================================================
# ERROR: test_seal_with_auth (tpm2_tests.SmokeTest)
# ----------------------------------------------------------------------
# Traceback (most recent call last):
#   File \"/lava-5608585/0/tests/1_kselftest-livepatch/automated/linux/kselftest/output/tpm2/tpm2_tests.py\", line 26, in test_seal_with_auth
#     blob = self.client.seal(self.root_key, data, auth, None)
#   File \"/lava-5608585/0/tests/1_kselftest-livepatch/automated/linux/kselftest/output/tpm2/tpm2.py\", line 620, in seal
#     rsp = self.send_cmd(cmd)
#   File \"/lava-5608585/0/tests/1_kselftest-livepatch/automated/linux/kselftest/output/tpm2/tpm2.py\", line 397, in send_cmd
#     raise ProtocolError(cc, rc)
# tpm2.ProtocolError: TPM_RC_LOCKOUT: cc=0x00000153, rc=0x00000921
```

This issue has been observed on grunt and sona so far.

The issue can be worked around by running `tpm2_clear` from the `tpm2-tools` package before running the tests, however [that solution is not acceptable upstream](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=5be206eaac9a68992fc3b06fb5dd5634e323de86). So the root cause of the issue might need to be investigated so that a proper solution can be sent upstream.

**Comment by padovan** [comment]
Old issue. (also we are not tracking kernel test failure/issues through GitHub anymore)
