### ISSUE TITLE
Remove warning while building selftest/futex with compressed file creation

### ISSUE THREAD

**Issue by musamaanjum** [kernelci/kernelci-project#104]
```
make -C tools/testing/selftests gen_tar -j 32
make[1]: Entering directory '/tmp/kci/linux/tools/testing/selftests/futex'
make[2]: Entering directory '/tmp/kci/linux/tools/testing/selftests/futex/functional'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/tmp/kci/linux/tools/testing/selftests/futex/functional'
mkdir -p /tmp/kci/linux/build/kselftest/kselftest_install/futex
install -t /tmp/kci/linux/build/kselftest/kselftest_install/futex run.sh  
make[2]: Entering directory '/tmp/kci/linux/tools/testing/selftests/futex'
make[2]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
rsync -a run.sh /tmp/kci/linux/build/kselftest/kselftest_install/futex/functional/
```
Reference: https://storage.staging.kernelci.org/kernelci/staging-next/staging-next-20220301.0/x86_64/x86_64_defconfig+x86-chromebook+kselftest/gcc-10/logs/kselftest.log

**Comment by musamaanjum** [comment]
I'm getting this warning `make[2]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.` when I pass `-jN`. Both of following commands give this warning:
```
make OUTPUT=$$BUILD_TARGET -C $$SUBDIR INSTALL_PATH=$(INSTALL_PATH)/$$SUBDIR install; \

or

$(MAKE) OUTPUT=$$BUILD_TARGET -C $$SUBDIR INSTALL_PATH=$(INSTALL_PATH)/$$SUBDIR install; \
```
Using `$(MAKE)` should have removed this warning ([[ https://www.gnu.org/software/make/manual/html_node/Error-Messages.html | Reference ]]). But no luck.

**Comment by musamaanjum** [comment]
Reported upstream: https://lore.kernel.org/linux-kselftest/8907d4a9-2a3f-3442-2c5e-6c34f196d2a8@collabora.com/

I'll wait to see if I get some feedback.

**Comment by padovan** [comment]
Old issue. (also we are not tracking kernel test failure/issues through GitHub anymore)
