### ISSUE TITLE
Enable HTTPs caching for rootfs builders

### ISSUE THREAD

**Issue by laura-nao** [kernelci/kernelci-project#107]
We're working on adding support for V4L2 decoder tests in KernelCI and we are using [fluster](https://github.com/fluendo/fluster) to download publicly available test vectors and run the conformance tests. The test vectors are downloaded from different providers (e.g. Webm git, ITU servers - full list is [here](https://github.com/fluendo/fluster/tree/master/test_suites)) and they need to be stored in the rootfs.

Would it be possible to enable HTTP(s) caching (e.g. in the KernelCI server where the rootfs images are created or in a server on the same network) and make it available to the rootfs builders? This would speed up the rootfs build process and compensate for any instability in the servers that provide the test vectors.

**Comment by gctucker** [comment]
This would be a requirement to implement https://github.com/kernelci/kernelci-core/issues/866 (V4L2 decoder coverage).

**Comment by laura-nao** [comment]
HTTP caching has been enabled and is now in use (see: https://github.com/kernelci/kernelci-core/blob/main/config/rootfs/debos/scripts/bullseye-gst-fluster.sh#L27).

Closing this issue.
