### ISSUE TITLE
Multiple x86 chromebooks failing to boot cros:// 6.1 kernel build with clang-16

### ISSUE THREAD

**Issue by nuclearcat** [kernelci/kernelci-project#166]
Kernel 6.1 built with clang-16 with options:
kci_build make_config --defconfig="cros://chromeos-6.1/x86_64/chromeos-intel-pineview.flavour.config+x86-chromebook+CONFIG_MODULE_COMPRESS_GZIP=n"
Fails to boot on Chromebook (asus-cx9400-volteer in this particular case).
https://lava.collabora.dev/scheduler/job/8849580
Last message is:
```

Command line loaded dynamically from TFTP file: 8849580/tftp-deploy-oy2441is/kernel/cmdline
The command line is: console_msg_format=syslog console=ttyS0,115200n8 root=/dev/nfs rw nfsroot=192.168.201.1:/var/lib/lava/dispatcher/tmp/8849580/extract-nfsrootfs-he4nt00v,tcp,hard ip=dhcp tftpserverip=192.168.201.1
Shutting down all USB controllers.
Removing current net device
Finalizing coreboot
Exiting depthcharge with code 4 at timestamp: 37436132
Starting kernel ...
end: 2.2.4 bootloader-commands (duration 00:00:29) [modules]
```
Kernel built with different options, such as x86_64_defconfig , or kernel v6.0 boots fine.

**Comment by gctucker** [comment]
Can we get these results on chromeos.kernelci.org as well with the regular kernel builds there rather than a hand-crafted one?

**Comment by nuclearcat** [comment]
I have them, but problem is that this link will expire: https://chromeos.kernelci.org/test/job/kernelci/branch/chromeos-stable/kernel/chromeos-stable-20230121.1/
It can be seen in baseline tests:
https://chromeos.kernelci.org/test/job/kernelci/branch/chromeos-stable/kernel/chromeos-stable-20230121.1/plan/baseline/

**Comment by nuclearcat** [comment]
Bisected issue, found discussion by commit id: 706460a96fc654e80b6bed1f562b00d2ce9f2f4d
https://lore.kernel.org/lkml/Y8lL95T93g5xK+mu@hirez.programming.kicks-ass.net/T/
It seems patch is pending, on the way to -stable since few days ago.

**Comment by padovan** [comment]
Old issue. (also we are not tracking kernel test failure/issues through GitHub anymore)
