### ISSUE TITLE
Fix Chrome browser rebuilds in kci_rootfs

### ISSUE THREAD

**Issue by 10ne1** [kernelci/kernelci-project#175]
When building the ChromiumOS images via `kci_rootfs`, the ChromeOS-Chrome browser gets rebuilt which takes a significant amount of time and resources on each build.

I've tested a latest main branch ChromiumOS build (`--usepkg` enabled which is the default) outside `kci_rootfs` and the Chrome browser is not rebuilt as is expected, so it's very likely something we do in `kci_rootfs` which is triggering the rebuilds (maybe enabling serial console in the image build or setting some use flag, something totally unrelated perhaps).

This is likely a bug in the ChromiumOS portage overlays, but I think it's worth eventually fixing it to make builds faster.

**Comment by padovan** [comment]
old issue
