### ISSUE TITLE
loongson2k_defconfig fails with make modules_install

### ISSUE THREAD

**Issue by gctucker** [kernelci/kernelci-project#176]
When doing `make modules_install`, the following error happens:
```
cc1: error: '-mloongson-mmi' must be used with '-mhard-float'
```
Sample build showing the problem:
https://linux.kernelci.org/build/id/63e1f1f2c405d78ea08c8633/
https://storage.kernelci.org/tip/master/v6.2-rc7-273-gd67c17ddc899/mips/loongson2k_defconfig/gcc-10/logs/modules.log

Email thread:
https://lore.kernel.org/kernelci/Y+JU07y+lvYAtZQT@sirena.org.uk/T/

**Comment by padovan** [comment]
Old issue. (also we are not tracking kernel test failure/issues through GitHub anymore)
