### ISSUE TITLE
Create systemd service definition for Dozzle

### ISSUE THREAD

**Issue by mgalka** [kernelci/kernelci-project#180]
There is a docker container running [Dozzle](https://dozzle.dev/) for publishing logs from containers running new KernelCI API and pipeline staging instance at https://staging.kernelci.org:9088.

A systemd service should be created to automate running, stopping and restarting docker container running Dozzle with appropriate options on KernelCI staging instance.

**Comment by gctucker** [comment]
For the record, the command to run Dozzle on staging is:
```
docker run --detach --volume=/var/run/docker.sock:/var/run/docker.sock -p 9089:8080 amir20/dozzle --filter name=kernelci-api --filter name=kernelci-pipeline
```

Then there's an Nginx proxy config in `sites-available/staging.kernelci.org:9088` to serve it on the public port 9088.

**Comment by gctucker** [comment]
Alright I've created the service file as it's about the 3rd time the VM is restarted or something and it had to be restarted manually:
```
kernelci@kernelci-staging:~$ cat /etc/systemd/system/dozzle.service
[Unit]
Description=Dozzle

[Service]
Type=oneshot
User=kernelci
ExecStart=docker run --detach --volume=/var/run/docker.sock:/var/run/docker.sock -p 9089:8080 amir20/dozzle --filter name=kernelci-api --filter name=kernelci-pipeline
```
@VinceHillier Please add this to any existing configuration management if we have that already and check it's setup to start automatically when the VM boots.  Then I guess this can be closed.

One thing, I'm not sure what's the best way to update the Docker image.  We could do a `docker pull` as part of ExecStart or rely on a tag and update it explicitly when we want to upgrade.  The same thing likely applies to other services running in a container e.g. Grafana.

**Comment by VinceHillier** [comment]
Completed by @gctucker

**Comment by gctucker** [comment]
Note: There was a bit missing as the service wasn't started automatically at boot time.  I think it should be fixed now but I haven't rebooted the VM to completely verify that.
