### ISSUE TITLE
Prepare script for cleaning unnecessary artifacts for staging instance of KernelCI API and pipeline

### ISSUE THREAD

**Issue by mgalka** [kernelci/kernelci-project#181]
Due to increased activity  around KernelCI API and pipeline there are more artifacts produced by this software components.

Script for periodically deleting unnecessary artifacts should be created in a similar way as it's done for other staging services.

Tasks

- [ ] Decide which artifacts should be deleted periodically and determine the time period for which they should be stored
- [ ] Prepare a script for cleaning up API and pipeline space
- [ ] Prepare necessary services and timers to run the cleaning job

**Comment by padovan** [comment]
Outdated.
