### ISSUE TITLE
TPM issue on Chromebooks: TPM in field failure mode, requires firmware upgrade

### ISSUE THREAD

**Issue by nuclearcat** [kernelci/kernelci-project#182]
Sometimes TPM is failing to detect with message:
For example: https://storage.staging.kernelci.org/kernelci/staging-next/staging-next-20230309.0/x86_64/x86_64_defconfig+x86-chromebook+ima/clang-17/lab-collabora/baseline-hp-11A-G6-EE-grunt.html
Linux version 6.3.0-rc1-next-20230308 (KernelCI@build-j67499-x86-64-clang-17-x86-64-defconfig-x86-chromebo2dk75) (Debian clang version 17.0.0 (++20230305071747+7abf6c2524d0-1~exp1~20230305071855.583), Debian LLD 17.0.0) #1 SMP PREEMPT_DYNAMIC Thu Mar  9 01:23:33 UTC 2023
[baseline-hp-11A-G6-EE-grunt-tpm.txt](https://github.com/kernelci/kernelci-project/files/10929190/baseline-hp-11A-G6-EE-grunt-tpm.txt)

```
<6>[    3.120944] cr50_i2c i2c-GOOG0005:00: cr50 TPM 2.0 (i2c 0x50 irq 27 id 0x28)
<6>[    3.185177] tsc: Refined TSC clocksource calibration: 1597.003 MHz
<6>[    3.191626] clocksource: tsc: mask: 0xffffffffffffffff max_cycles: 0x170515c4cec, max_idle_ns: 440795217416 ns
<3>[    3.194005] tpm tpm0: Operation Timed out
<6>[    3.206141] tpm tpm0: TPM in field failure mode, requires firmware upgrade
```
This happens rarely, randomly, at different kernel versions.

**Comment by padovan** [comment]
Old issue. (also we are not tracking kernel test failure/issues through GitHub anymore)
