### ISSUE TITLE
Staging Migration to new Azure Subscription

### ISSUE THREAD

**Issue by VinceHillier** [kernelci/kernelci-project#194]
Expanding on #179 

# Staging Migration Plan
Staging has ~550GB of data, previous transfers took 16m per 500G.  It should be less than 20 minutes to transfer staging.

Pre window tasks:

- [x] Create new public IP for staging on new subscription 
20.106.209.98
- [x] Reduce TTL for staging.kernelci.org from 3600 to 600.
- [x] Schedule DNS update with LF determining T:0
- [x] Prepare NSG ruleset for post migration

T: 0m
1. Shutdown staging vm
1. Snapshot osDisk and data disk
1. Update IP address for (api.)staging.kernelci.org in DNS
T:+20m
1. Transfer snapshots to new subscription
T:+50m
1. Create disks based off snapshots (staging disk should be 1TB)
1. Create VM with osDisk and data disk, assign new public IP
T:+70m
1. Update NSG to match previous rules
1. Update Zabbix monitoring to use new IP
T:+80m

**Comment by gctucker** [comment]
I guess this is specifically about the staging.kernelci.org VM?

**Comment by VinceHillier** [comment]
> I guess this is specifically about the staging.kernelci.org VM?

Correct

**Comment by VinceHillier** [comment]
This has been completed.

**Comment by gctucker** [comment]
I believe we still need to update the DNS records with the longer TTLs and do some clean-up with the old subdomains.  But that's a separate task, I don't think there's a GitHub issue for it yet.
