### ISSUE TITLE
db6f68b51e5c media: verisilicon: Do not set context src/dst formats in reset functions

### ISSUE THREAD

**Issue by crazoes** [kernelci/kernelci-project#196]
- **Commit**: https://lore.kernel.org/all/20230220104849.398203-2-benjamin.gaignard@collabora.com/
- **Regressions**: https://linux.kernelci.org/test/case/id/6442e825f19134d74c2e865d/
- **Email**: https://groups.io/g/kernelci-results/message/40740
- **Bisection Report**:

```
Summary:
  Start:      009795d283d1 Add linux-next specific files for 20230411
  Plain log:  https://storage.kernelci.org/next/master/next-20230411/arm64/defconfig+ima/gcc-10/lab-collabora/baseline-rk3399-rock-pi-4b.txt
  HTML log:   https://storage.kernelci.org/next/master/next-20230411/arm64/defconfig+ima/gcc-10/lab-collabora/baseline-rk3399-rock-pi-4b.html
  Result:     db6f68b51e5c media: verisilicon: Do not set context src/dst formats in reset functions

Checks:
  revert:     PASS
  verify:     PASS

Parameters:
  Tree:       next
  URL:        https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git
  Branch:     master
  Target:     rk3399-rock-pi-4b
  CPU arch:   arm64
  Lab:        lab-collabora
  Compiler:   gcc-10
  Config:     defconfig+ima
  Test case:  baseline.dmesg.alert
  ```
  
  cc @hardboprobot @gctucker @padovan

**Comment by crazoes** [comment]
Reported here :- https://lore.kernel.org/lkml/26addb7d-bb9d-34e8-d4fe-e323ff488101@collabora.com/
Fixed :- https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git/commit/?h=master&id=f100ce3bbd6aa0093075b20b9dbd006686f6aedf

**Comment by padovan** [comment]
Old issue. (also we are not tracking kernel test failure/issues through GitHub anymore)
