### ISSUE TITLE
88b61e3bff93 Makefile.compiler: replace cc-ifversion with compiler-specific macros

### ISSUE THREAD

**Issue by crazoes** [kernelci/kernelci-project#197]
- **Commit**: https://lore.kernel.org/all/20220919170828.3718437-1-ndesaulniers@google.com/
- **Regressions**: https://linux.kernelci.org/test/case/id/644596a0beca2ead032e8669/
- **Email**: https://groups.io/g/kernelci-results/message/40804
- **Bisection Report**:
```
Summary:
  Start:      e62252bc55b6 Merge tag 'pci-v6.3-fixes-2' of git://git.kernel.org/pub/scm/linux/kernel/git/pci/pci
  Plain log:  https://storage.kernelci.org/mainline/master/v6.3-rc6-34-ge62252bc55b6/arm/multi_v7_defconfig+debug/gcc-10/lab-collabora/baseline-qemu_arm-virt-gicv3-uefi.txt
  HTML log:   https://storage.kernelci.org/mainline/master/v6.3-rc6-34-ge62252bc55b6/arm/multi_v7_defconfig+debug/gcc-10/lab-collabora/baseline-qemu_arm-virt-gicv3-uefi.html
  Result:     88b61e3bff93 Makefile.compiler: replace cc-ifversion with compiler-specific macros

Checks:
  revert:     PASS
  verify:     PASS

Parameters:
  Tree:       mainline
  URL:        https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git
  Branch:     master
  Target:     qemu_arm-virt-gicv3-uefi
  CPU arch:   arm
  Lab:        lab-collabora
  Compiler:   gcc-10
  Config:     multi_v7_defconfig+debug
  Test case:  baseline.login
  ```
  
  cc @hardboprobot @padovan @gctucker

**Comment by crazoes** [comment]
Converstations related to the regression :-
https://lore.kernel.org/lkml/87353ok78h.fsf@rcn-XPS-13-9305.i-did-not-set--mail-host-address--so-tickle-me/

**Comment by crazoes** [comment]
First LAVA job that was reported to Nick :- https://lava.collabora.dev/scheduler/job/10135631

**Comment by crazoes** [comment]
It has been fixed upstream but the commit is unknown to us.

**Comment by gctucker** [comment]
Sounds like a typical scenario for a reverse bisection.

**Comment by crazoes** [comment]
@gctucker yes I think people might not want to spend time on finding the fix commit after it is resolved. In that case it is good to have reverse bisection.

**Comment by gctucker** [comment]
And then have a check at the end to apply the found fix on top of the revision initially bisected with the bug to see if it actually fixes the problem - we might be surprised of the result in some cases, like another bug making the first one disappear etc.  It's part of the ever-growing "post-regression checks" category.
