### ISSUE TITLE
v6.3-12728-g348551ddaf31  mt8183-kukui-jacuzzi-juniper-sku16 fails to boot current mainline builds / loops in mt8183_mt6358_ts3a227

### ISSUE THREAD

**Issue by nuclearcat** [kernelci/kernelci-project#202]
mt8183-kukui-jacuzzi-juniper-sku16 fails to boot current mainline builds, for example:

https://staging.kernelci.org/test/plan/id/6451e6a09b1d457c3b134ce1/
Tree
    mainline — 
Git branch
    master — 
Git describe
    v6.3-12728-g348551ddaf31 

Boot logs:
https://storage.staging.kernelci.org/mainline/master/v6.3-12728-g348551ddaf31/arm64/defconfig+arm64-chromebook/gcc-10/lab-collabora/baseline-nfs-mt8183-kukui-jacuzzi-juniper-sku16.html
https://storage.staging.kernelci.org/mainline/master/v6.3-12728-g348551ddaf31/arm64/defconfig+arm64-chromebook/gcc-10/lab-collabora/baseline-nfs-mt8183-kukui-jacuzzi-juniper-sku16.html

Reason probably related to message that are looping on boot:
```
 3600 04:44:03.381031  <6>[  264.657658] mt8183_mt6358_ts3a227 mt8183-sound: mt8183_mt6358_ts3a227_max98357_dev_probe Can't find pin state wov -19
 3601 04:44:03.495904  <6>[  264.772604] mt8183_mt6358_ts3a227 mt8183-sound: mt8183_mt6358_ts3a227_max98357_dev_probe Can't find pin state wov -19
 3602 04:44:03.612836  <6>[  264.889705] mt8183_mt6358_ts3a227 mt8183-sound: mt8183_mt6358_ts3a227_max98357_dev_probe Can't find pin state wov -19
 3603 04:44:03.729553  <6>[  265.006213] mt8183_mt6358_ts3a227 mt8183-sound: mt8183_mt6358_ts3a227_max98357_dev_probe Can't find pin state wov -19
 3604 04:44:03.844547  <6>[  265.121248] mt8183_mt6358_ts3a227 mt8183-sound: mt8183_mt6358_ts3a227_max98357_dev_probe Can't find pin state wov -19
 3605 04:44:03.960552  <6>[  265.237378] mt8183_mt6358_ts3a227 mt8183-sound: mt8183_mt6358_ts3a227_max98357_dev_probe Can't find pin state wov -19
```

* Commit: https://github.com/torvalds/linux/commit/<git sha1> `<git subject>`
* Regressions:
  * https://linux.kernelci.org/test/case/id/<id>/
  * https://linux.kernelci.org/test/case/id/<id>/
* Email: https://lore.kernel.org/lkml/<thread>
* Bisection report:
```
<Summary from email>
```

**Comment by padovan** [comment]
Old issue. (also we are not tracking kernel test failure/issues through GitHub anymore)
