### ISSUE TITLE
Jitsi migration / upgrade

### ISSUE THREAD

**Issue by VinceHillier** [kernelci/kernelci-project#216]
Our jitsi service hosted at https://meet.kernel.social needs to be moved to our new Azure subscription as the current subscription expires later this week.

Additionally, the service is quite dated. We'll explore upgrading it as well.

- [x] snapshot existing vms and transfer to new subscription
- [x] examine existing disks to duplicate configuration
- [ ] deploy new jitsi service
- [ ] update dns eastus-jitsi.eastus.cloudapp.azure.com

**Comment by VinceHillier** [comment]
@gctucker I think it's safe to say at this point that we no longer require this?  If so, I'll delete the jitsi vm and we can continue using meet.jit.si.

**Comment by gctucker** [comment]
I still need to ping Konstantin to close the loop on this.  Then I think we might need a TSC vote to confirm we're OK with using meet.jit.si rather than a self-hosted one.

**Comment by padovan** [comment]
we have been using meet.jitsi.si for a while already.
