### ISSUE TITLE
I cannot follow steps to add a LAVA lab to my local kernelci instance

### ISSUE THREAD

**Issue by lufy90** [kernelci/kernelci-project#223]
I read a lot kernelci documentation, but still cannot add my lava to my private kernelci instance.
I tried to follow steps at [steps-to-add-a-lava-lab-to-kernelciorg](https://kernelci.org/docs/labs/lava/#steps-to-add-a-lava-lab-to-kernelciorg), but [lab-configs.yaml](https://github.com/kernelci/kernelci-core/blob/main/config/core/lab-configs.yaml) was removed. I thought even file `lab-configs.yaml` exists, it is a static file in [kernelci-core](https://github.com/kernelci/kernelci-core), how kernelci-backend read this? Really confused, need help.

**Comment by nuclearcat** [comment]
Thank you for reporting issue, this is because of a bit outdated documentation. I sent PR to fix that.

**Comment by lufy90** [comment]
Thank a lot for reply. I still not clear: `runtime-configs.yaml`  is located in github kernelci-core code. Where it should be in my local system(a private kernelci instance) to make sense?
