### ISSUE TITLE
Broken links in the Kernel CI Test Plans page

### ISSUE THREAD

**Issue by isaiahduncan** [kernelci/kernelci-project#23]
https://github.com/kernelci/kernelci-doc/wiki/Build-configurations

![image](https://user-images.githubusercontent.com/32970507/125665466-fa4078d0-d428-4db3-b60c-cd53fb21ecf4.png)

In the above photo the two highlighted links go to pages that that say they are no longer valid. 

Also the file links in the screenshot (eg. "test-configs.yaml") don't work.

**Comment by gctucker** [comment]
> https://github.com/kernelci/kernelci-doc/wiki/Test-configurations
> Also all of the links on the Test Configurations page except for the very first one do not work

The content of the wiki is being moved to the new documentation section now on https://kernelci.org/docs/ so that page should be removed eventually.  Thanks for spotting such issues.

**Comment by Lakshmipathi** [comment]
Updated broken links on https://github.com/kernelci/kernelci-doc/wiki/KernelCI @isaiahduncan  Let me know if you find something missing or wrong. thanks

**Comment by gctucker** [comment]
That page on the wiki is being removed.  Instead, there's the Tests section in the new documentation and this page about how to add a new one: https://kernelci.org/docs/tests/howto/
