### ISSUE TITLE
Request API account for aratiu, aferraris, nuclearcat

### ISSUE THREAD

**Issue by nuclearcat** [kernelci/kernelci-project#244]
I would like to request API early access for ChromeOS instance development:

* User name: aratiu
* Email address: adrian.ratiu@collabora.com

* User name: aferraris
* Email address: arnaud.ferraris@collabora.com

* User name: nuclearcat
* Email address: denys.f@collabora.com

Thank you

**Comment by gctucker** [comment]
OK, it's better to have one issue per account and ideally the issue should be created by the user requesting the account.  I know the other 2 people so it's fine but please follow the documented steps for creating accounts going forward, if someone wants one they should create their own issue.

**Comment by gctucker** [comment]
Confirmation emails sent for the 3 users.  Enjoy :)
