### ISSUE TITLE
Automated bisection base coverage

### ISSUE THREAD

**Issue by gctucker** [kernelci/kernelci-project#260]
After reducing the costs when moving to the new Azure subscription, automated bisections were disabled in order to keep costs in a safe zone.  We've now evaluated the costs of running the dedicated VM for bisections again and have agreed on a way forward by only enabling it on mainline, linux-next, stable and stable-rc trees.

The plan is to have this done for next Monday's production update:

- [x] Start the dedicated VM again
- [x] Enable the Jenkins CasC section for the bisection runner
- [x] Adjust Jenkins job parameters to filter out other trees than the ones listed above
- [x] Add filter in kernelci-backend to avoid filling the Jenkins queue with jobs that then get cancelled
- [x] Verify on staging
- [x] Merge all changes ahead of the production update

**Comment by gctucker** [comment]
@VinceHillier Here's the Jenkins settings section from `/etc/kernelci/kernelci-celery.cfg` used on staging:
```json
    "jenkins_options": {
        "url": "https://bot.staging.kernelci.org/",
        "user": "bisection",
        "bisect": "lava-bisection",
        "token": "<TOKEN>",
        "bisection-git-trees": ["gtucker"]
    },
```

Similarly, please add this item in the file used in production before doing the Monday update:
```json
        "bisection-git-trees": ["kernelci", "mainline", "next", "stable", "stable-rc"]
```

The same list of trees is already configured in the Jenkins `env` files so that should get applied automatically when restarting Jenkins during the production update.

The bisection Jenkins runner appears to have been enabled again already in `nodes.yaml` and the matching VM is `kernelci-prod-jenkins-runner-1.westus3.cloudapp.azure.com` so please just make sure it's up and running before starting the production update.

I think that's all that's needed, we should then start to see bisections for these trees only in the Jenkins queue when regressions get detected.  Probably we could artificially create one on the `kernelci` tree after a day or two if we're not seeing any real ones, at least this has all been tested on staging.

**Comment by nuclearcat** [comment]
Dedicated VM enabled, jenkins showing node status online, will check tomorrow if any jobs queued

**Comment by gctucker** [comment]
OK at least one bisection job completed in production about 8h ago:
https://groups.io/g/kernelci-results/message/47247
```
d6d6c513f5d2d14651336fb4e30f097822b46f29 is the first bad commit
commit d6d6c513f5d2d14651336fb4e30f097822b46f29
Author: Xingyu Wu <xingyu.wu@starfivetech.com>
Date:   Mon Aug 21 22:41:48 2023 +0800

    ASoC: dwc: Use ops to get platform data
    
    Use of_device_get_match_data() to get platform data.
    
    Signed-off-by: Xingyu Wu <xingyu.wu@starfivetech.com>
    Link: https://lore.kernel.org/r/20230821144151.207339-3-xingyu.wu@starfivetech.com
    Signed-off-by: Mark Brown <broonie@kernel.org>
```
