### ISSUE TITLE
Legacy how-to points to invalid URL

### ISSUE THREAD

**Issue by trini** [kernelci/kernelci-project#307]
In `kernelci.org/content/en/docs/legacy/how-to.md` it says "A good way to start prototyping things is to use the plain [Debian Buster NFS rootfs](https://storage.kernelci.org/images/rootfs/debian/buster/)" but that should now point to bullseye instead.

**Comment by gctucker** [comment]
@nuclearcat Could you please take a look?  Or let me know if you prefer that I assign it to myself instead.

**Comment by nuclearcat** [comment]
I guess i will need to update all references from buster to bullseye within the file?
P.S. We started to migrate to Bookworm, maybe better to update directly to it? Initial tests show most of the builds are fine.

**Comment by gctucker** [comment]
I don't know, if you can take care of solving this issue then please do otherwise I'll take a look.  I think it should be fixed now regardless of future changes.

**Comment by gctucker** [comment]
@trini Hello, an updated version of the How-To is now available here:
https://static.staging.kernelci.org/docs/legacy/how-to/

If this looks good it should be deployed on the main website on Monday.  If you have the time to take a look, please feel free to leave any comment or review the #308 PR.
