### ISSUE TITLE
Add TSC member: Paweł Wieczorek

### ISSUE THREAD

**Issue by gctucker** [kernelci/kernelci-project#315]
Here's the checklist for adding @pawiecz (Paweł Wieczorek) as TSC member:

- [x] TSC voting record added to the documentation
- [x] TSC documentation page updated with new member's name, email and IRC nickname
- [x] New member invited to join `kernelci-tsc@groups.io`
- [x] New member invited to the monthly TSC meeting
- [x] New member invited to any relevant Slack private channels (if applicable)
- [x] Induction about TSC role with Chair or other committee members completed

Note: This issue may then be used as a template for future TSC members to add (or remove with the negative version).

**Comment by padovan** [comment]
@nuclearcat volunteered to take care of the TSC intro. Then I am still waiting information about the TSC private channel.

**Comment by gctucker** [comment]
I've made a PR to add an issue template based on this: https://github.com/kernelci/kernelci-project/pull/318

**Comment by padovan** [comment]
Folder also shared with Pawel.

All steps are complete now!

**Comment by gctucker** [comment]
> Folder also shared with Pawel.

Ah I guess that's covered by the item I added last week "TSC documents shared with the new member", let's see if there's anything still missing in issue about adding Shuah.
