### ISSUE TITLE
Link to contribution guidelines on main page is broken

### ISSUE THREAD

**Issue by threexc** [kernelci/kernelci-project#316]
Getting a 404 when I click "Read more" under "Contribute data" on the KernelCI webpage. Looks like the proper link should be: https://github.com/kernelci/kcidb/blob/main/doc/submitter_guide.md

Tried creating a fork and submitting a PR, but I can't seem to push to the fork (possibly because of LFS?).

**Comment by gctucker** [comment]
Thanks for reporting this.

I think the actual link should be this:
https://kernelci.org/docs/kcidb/submitter_guide/

so `/docs/kcidb/submitter_guide/` for a relative path in the HTML link from the kernelci.org home page.

@spbnick What do you think?

**Comment by padovan** [comment]
After the docs refactor that page doesn't exist anymore, so this issues is not relevant anymore.
