### ISSUE TITLE
Add TSC member: Shuah Khan

### ISSUE THREAD

**Issue by padovan** [kernelci/kernelci-project#325]
Please go through all the checklist below to add @shuahkh (Shuah Khan) as a member of the [TSC](https://kernelci.org/docs/org/tsc/):

- [x] #326
  - [x] [TSC voting record](https://kernelci.org/docs/org/tsc/votes/) added to the documentation
  - [x] [TSC members](https://kernelci.org/docs/org/tsc/#members) documentation updated with new member's name, email and IRC nickname
- [x] New member invited to join [`kernelci-tsc@groups.io`](https://groups.io/g/kernelci-tsc)
- [x] New member invited to the [monthly TSC meeting](https://kernelci.org/docs/org/#technical-steering-committee)
- [x] TSC documents shared with the new member (meeting minutes in Google Docs etc.)
- [x] New member invited to any relevant [Slack](https://kernelci.slack.com) private channels (if applicable)
- [x] Induction about [TSC rules and duties](https://kernelci.org/docs/org/tsc/#rules) with Chair or other committee members completed

**Comment by gctucker** [comment]
Confirmed that the website was updated as expected yesterday: https://kernelci.org/docs/org/tsc/
