### ISSUE TITLE
Deploy connecting lab documentation

### ISSUE THREAD

**Issue by JenySadadia** [kernelci/kernelci-project#338]
Initial documentation for connecting LAVA lab in the pipeline is added [here](https://github.com/kernelci/kernelci-pipeline/blob/main/doc/connecting-lab.md).

Deploy it on [kernelci.org/docs](kernelci.org/docs).

**Comment by nuclearcat** [comment]
Test comment

**Comment by nuclearcat** [comment]
test2

**Comment by JenySadadia** [comment]
I think we should move this doc to https://github.com/kernelci/kernelci-api/tree/main/doc to centralize all the API & Pipeline documentation under one repository.
What do you think? @pawiecz @nuclearcat

**Comment by pawiecz** [comment]
I understand the reason to keep all the docs in a single place. I also get that keeping several submodules in the `-project` is not always convenient. I'd still keep the pipeline configuration docs as close as possible to the relevant files, though (leaving kernelci/kernelci-pipeline#592 as it is).

To have the docs from kernelci/kernelci-pipeline#592 published there would be a need for another submodule. This, however, would also pull the [doc/result-summary-CHANGELOG](https://github.com/kernelci/kernelci-pipeline/blob/main/doc/result-summary-CHANGELOG) - is it still needed there?

There's one more thing that needs to be discussed but I'm not 100% sure what would be the best way to proceed with it: connecting labs also involves some sysadmin work/secret management. I believe having a public process for that would increase transparency - do you think this could be shared while still maintaining all necessary information secure?

**Comment by JenySadadia** [comment]
Okay. Your points make sense.
We can consider adding a submodule to `kernelci-project`.
But atm we included all the pipeline related documentation to `kernelci-api` repo. Should we need to move it to the pipeline repo as well?

**Comment by pawiecz** [comment]
Out of all the docs stored in the `kernelci-api` repo:

```
kernelci-api$ tree doc
doc
├── api-details.md
├── design.md
├── developer-documentation.md
├── early-access.md
├── _index.md
├── local-instance.md
└── pipeline-details.md
```

I'd move only `developer-documentation.md` (**after** the submodule is enabled) as that guide mostly covers changes to the `config/pipeline.yaml` file from `-pipeline` repository.

We'd still be able to have it easily accessible (as the rendered content on Hugo) and point external labs admins/other contributors there.

**Comment by JenySadadia** [comment]
We'd also need to move `pipeline-details` page as it describes pipeline services. `local-instance` page also has a pipeline instance setup documentation.

**Comment by pawiecz** [comment]
Agreed 100% on `pipeline-details`. I'm a bit torn on `local-instance` as it covers setup of both components and still uses API as the main "user interface". On top of this, I'm afraid that splitting the guide could bring more confusion than clarity.

**Comment by JenySadadia** [comment]
All the related PRs have been merged.
