### ISSUE TITLE
Use markdown mermaid diagrams in documentation

### ISSUE THREAD

**Issue by nuclearcat** [kernelci/kernelci-project#347]
Mermaid diagrams supported in github markdown parsing, and probably hugo can support it too, so we can have nice diagrams like this:

![mermaid-diagram-2024-05-02-165628](https://github.com/kernelci/kernelci-project/assets/1076310/33512cdc-3991-4f2b-832b-4c9e3c3da319)
This link clickable and points to live editor:
[![](https://mermaid.ink/img/pako:eNpVjctugzAQRX8FzZqggDENXlRqQr6gXRWzcPAAVvyIwFabIv69lEhVO6u551zNzNA6icCg0-6jHcToo7eK22idl7odsL264Jtot3uOjvX1EpSWzUP_xk2e5ouYUCuLy0OfNlzV2vXKNn_ZuZYGp76BGAyORii5vp9_Ghz8gAY5sHWV2ImgPQdul7Uqgnevd9sC82PAGMJNCo-VEv0oDLBO6GmlN2HfnfuXgc3wCYzkRZIVZUEJyfYkzWgMd2BZekgOaZnRssgJpfnTEsPXdmCf0OUbDrVWyw?type=png)](https://mermaid.live/edit#pako:eNpVjctugzAQRX8FzZqggDENXlRqQr6gXRWzcPAAVvyIwFabIv69lEhVO6u551zNzNA6icCg0-6jHcToo7eK22idl7odsL264Jtot3uOjvX1EpSWzUP_xk2e5ouYUCuLy0OfNlzV2vXKNn_ZuZYGp76BGAyORii5vp9_Ghz8gAY5sHWV2ImgPQdul7Uqgnevd9sC82PAGMJNCo-VEv0oDLBO6GmlN2HfnfuXgc3wCYzkRZIVZUEJyfYkzWgMd2BZekgOaZnRssgJpfnTEsPXdmCf0OUbDrVWyw)

**Comment by JenySadadia** [comment]
Yes, we already have a bunch of mermaid digrams for API and Pipeline docs. See https://kernelci.org/docs/api/pipeline-details/
