### ISSUE TITLE
Request API account for andersson

### ISSUE THREAD

**Issue by andersson** [kernelci/kernelci-project#429]
Please provide access such that I can migrate lab-bjorn from the old KernelCI API.

* User name: andersson
* Email address: andersson@kernel.org

**Comment by JenySadadia** [comment]
Hello,
I have created API user account for staging instance.
A confirmation email is sent with credentials and other information.

**Comment by JenySadadia** [comment]
Hello @andersson 

Once you setup your local pipeline instance, you can subscribe to `node` channel with `promisc` flag enabled.
You can use `self._api.subscribe('node', True)` from the implementation https://github.com/kernelci/kernelci-core/pull/2629 in your pipeline service.
Then you can use `kind=kbuild` to filter build nodes from the events.
