### ISSUE TITLE
Create/Update the dashboard to show compatible strings

### ISSUE THREAD

**Issue by musamaanjum** [kernelci/kernelci-project#438]
Jeny has added a compatible string to KCIDB in https://github.com/kernelci/kernelci-pipeline/issues/761. Please create/update the dashboard to show the compatible strings.

cc: @JenySadadia @nuclearcat

**Comment by musamaanjum** [comment]
@helen-fornazier Unable to assign this issue to you.

**Comment by helen-fornazier** [comment]
Compatible is already in the home page and is listed when you click on the test result in grafana.
We also have it already in the official dashboard. I'm closing this issue, feel free to re-open it if there is anything left.
