### ISSUE TITLE
kbuild jobs are marked as incomplete with no logs

### ISSUE THREAD

**Issue by musamaanjum** [kernelci/kernelci-project#501]
https://kernelci-api.westus3.cloudapp.azure.com/viewer?search=parent%3D6757449c8b787efcb4b8752e has a lot of kbuild jobs which are marked as incomplete. If an incomplete node opens. There are no logs attached. (For example https://kernelci-api.westus3.cloudapp.azure.com/viewer?node_id=675746c48b787efcb4b87c37)

cc: @nuclearcat @pawiecz

**Comment by nuclearcat** [comment]
This was 1 day issue due introduced bug and we reversed production in 24h
```
    "error_code": "submit_error",
    "error_msg": "Invalid kube-config file. No configuration found."
```
