### ISSUE TITLE
`8c3d64251ac5` phy-rockchip-inno-usb2

### ISSUE THREAD

**Issue by gctucker** [kernelci/kernelci-project#55]
* Commit: https://github.com/torvalds/linux/commit/8c3d64251ac5c5a3d10364f6b07d3603ac1e7b4a `arm64: dts: rockchip: rename nodename for phy-rockchip-inno-usb2`
* Regressions:
  * https://linux.kernelci.org/test/case/id/614bafe313002ef68d99a340/
* Email: https://lore.kernel.org/lkml/c52f6cfb-1316-dd6a-46fa-17abfcc4bf18@collabora.com/
* Bisection report:
```
Summary:
  Start:      58e2cf5d7946 init: Revert accidental changes to print irqs_disabled()
  Plain log:  https://storage.kernelci.org/mainline/master/v5.15-rc2-51-g58e2cf5d7946/arm64/defconfig/gcc-8/lab-collabora/baseline-rk3399-gru-kevin.txt
  HTML log:   https://storage.kernelci.org/mainline/master/v5.15-rc2-51-g58e2cf5d7946/arm64/defconfig/gcc-8/lab-collabora/baseline-rk3399-gru-kevin.html
  Result:     8c3d64251ac5 arm64: dts: rockchip: rename nodename for phy-rockchip-inno-usb2

Checks:
  revert:     PASS
  verify:     PASS

Parameters:
  Tree:       mainline
  URL:        https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git
  Branch:     master
  Target:     rk3399-gru-kevin
  CPU arch:   arm64
  Lab:        lab-collabora
  Compiler:   gcc-8
  Config:     defconfig
  Test case:  baseline.bootrr.rockchip-usb2phy1-probed
```

**Comment by gctucker** [comment]
Proposed fix:
https://lore.kernel.org/lkml/5095423.31r3eYUQgx@diego/ `Annotation for dtbscheck to ignore a defect`

The discussion about this fix appears to be stale, the thread should be bumped.

**Comment by padovan** [comment]
Old issue. (also we are not tracking kernel test failure/issues through GitHub anymore)
