### ISSUE TITLE
`ea718c699055` mtk-mmsys-probed

### ISSUE THREAD

**Issue by gctucker** [kernelci/kernelci-project#57]
* Commit: https://github.com/torvalds/linux/commit/ea718c699055c8566eb64432388a04974c43b2ea `Revert "Revert "driver core: Set fw_devlink=on by default""`
* Regressions:
  * https://linux.kernelci.org/test/case/id/614cde60b98418f99e99a316/ (ulfh tree)
  * https://linux.kernelci.org/test/case/id/614baf48ac931dd30d99a2f0/ (lost tracked as regression on mainline)
* Email: https://lore.kernel.org/lkml/f13ff971-8af2-be9b-fa5d-7913c0ff1351@collabora.com/
* Bisection report:
```
Summary:
  Start:      8211999fc64c mmc: mmci: Add small comment about reset thread
  Plain log:  https://storage.kernelci.org/ulfh/next/v5.15-rc1-29-g8211999fc64c/arm64/defconfig/gcc-8/lab-collabora/baseline-mt8173-elm-hana.txt
  HTML log:   https://storage.kernelci.org/ulfh/next/v5.15-rc1-29-g8211999fc64c/arm64/defconfig/gcc-8/lab-collabora/baseline-mt8173-elm-hana.html
  Result:     ea718c699055 Revert "Revert "driver core: Set fw_devlink=on by default""

Checks:
  revert:     PASS
  verify:     PASS

Parameters:
  Tree:       ulfh
  URL:        https://git.kernel.org/pub/scm/linux/kernel/git/ulfh/mmc.git
  Branch:     next
  Target:     mt8173-elm-hana
  CPU arch:   arm64
  Lab:        lab-collabora
  Compiler:   gcc-8
  Config:     defconfig
  Test case:  baseline.bootrr.clk-mt8173-mm-probed
```

**Comment by gctucker** [comment]
The issue appears to be that the clock driver doesn't get probed, probably for a similar reason to this example:
https://lore.kernel.org/lkml/CAGETcx9PiX==mLxB9PO8Myyk6u2vhPVwTMsA5NkD-ywH5xhusw@mail.gmail.com/

This is the test case from bootrr:
https://github.com/kernelci/bootrr/blob/main/boards/google%2Chana#L24
```
assert_device_present clk-mt8173-mm-probed clk-mt8173-mm clk-mt8173-mm.*
```
The source code for the driver is `drivers/clk/mediatek/clk-mt8173-mm.c`.

**Comment by padovan** [comment]
Old issue. (also we are not tracking kernel test failure/issues through GitHub anymore)
