### ISSUE TITLE
Add documentation for `xymon`

### ISSUE THREAD

**Issue by gctucker** [kernelci/kernelci-project#62]
The `xymon` service is used to monitor KernelCI services.  Some documentation should be added to https://kernelci.org/docs/admin/ so sysadmins know how it's set up and how to keep it working.

**Comment by montjoie** [comment]
All xymon stuff is removed from staging.

**Comment by gctucker** [comment]
@montjoie Where was it by the way?

**Comment by montjoie** [comment]
It was only deployed on staging. I will check prod soon, but in my memory, I never started deploying on it due to missing answer to "how to do a secure link beween them".

**Comment by gctucker** [comment]
But I mean, where on the staging was it deployed?  Under which user, and how was it deployed?

**Comment by montjoie** [comment]
It was deployed by hand via:
- the xymon-client apt package (which is now removed via apt --purge)
- a docker with all data/dockerfile under ~/xymon for kernelci user. (the whole directory is now deleted)
I did a find on staging to verify nothing remains
