### ISSUE TITLE
`7c636d4d20f8` Network errors on mt8173-elm-hana

### ISSUE THREAD

**Issue by gctucker** [kernelci/kernelci-project#66]
* Commit: https://github.com/torvalds/linux/commit/7c636d4d20f8c5acfbfbc60f326fddb0e1cf5daa `Merge tag 'dt-5.15' of git://git.kernel.org/pub/scm/linux/kernel/git/soc/soc`
* Regressions:
  * https://linux.kernelci.org/test/case/id/61301759932662b5ded596a6/
* Email: https://lkml.org/lkml/2021/10/11/489
* Bisection report: The automated bisection landed on the merge commit mentioned above, which isn't the root cause of the problem.

**Comment by 10ne1** [comment]
Reverting [this commit](https://github.com/torvalds/linux/commit/109fd20601e2bdab641eec26e28351477f311ff0) will get network working again, likely it interacts badly with another commit introduced between v5.14 (where it works) and the `dt-5.15` tag.

**Comment by 10ne1** [comment]
@eballetbo Yes, that config change brings back usb networking. The reason why it worked before the breaking commit is that the always-on dummy regulator was used:

```
mtk-power-controller 10006000.syscon:power-controller: supply domain not found, using dummy regulator
mtu3 11271000.usb: supply vbus not found, using dummy regulator
xhci-mtk 11270000.usb: supply vbus not found, using dummy regulator
```

After [the commit](https://github.com/torvalds/linux/commit/7c636d4d20f8c5acfbfbc60f326fddb0e1cf5daa) the new regulator is used instead of dummy which is why it requires explicit enabling.

**Comment by 10ne1** [comment]
Patch sent upstream: https://lkml.org/lkml/2021/10/11/489

**Comment by gctucker** [comment]
Tested on staging:
https://staging.kernelci.org/test/plan/id/616945b4043bf9aafba6c453/

The patch was applied on the staging-mainline branch:
https://github.com/kernelci/linux/commit/77e710a6327735630ca43d86865c6472bfc10e56

**Comment by gctucker** [comment]
@10ne1 Hello, it looks like there hasn't been any replies from the maintainers.  Do you think this will get merged?

**Comment by gctucker** [comment]
Thanks, we can reply with tested-by kernelci.org and ask about any feedback.

If there's no sign that it might get merged then we would have to start considering a config fragment in KernelCI since the `hana` Chromebook can't boot a mainline kernel at the moment (as you know).

**Comment by gctucker** [comment]
I've added a config fragment to fix hana in production until the patch gets applied upstream:
https://github.com/kernelci/kernelci-core/pull/897
