### ISSUE TITLE
config fragment should list all dependent config options

### ISSUE THREAD

**Issue by musamaanjum** [kernelci/kernelci-project#83]
`merge_config.sh` doesn't produce desired results when a config fragment doesn't list all dependencies

Example:
`tools/testing/selftests/lkdtm/config` has the following config related to UBSAN:
```
CONFIG_UBSAN_BOUNDS=y
CONFIG_UBSAN_TRAP=y
```
These two configs depend on `CONFIG_UBSAN`. When the parent config doesn't have `CONFIG_UBSAN` enabled, these two configs are ignored with the following error. 
```
merge_config.sh .config source/tools/testing/selftests/lkdtm/config
Value requested for CONFIG_UBSAN_BOUNDS not in final .config
Requested value:  CONFIG_UBSAN_BOUNDS=y
Actual value:     

Value requested for CONFIG_UBSAN_TRAP not in final .config
Requested value:  CONFIG_UBSAN_TRAP=y
Actual value:
```
The desired result is to have `CONFIG_UBSAN` and these two configs enabled in this case which is only possible if `CONFIG_UBSAN` was also present in `tools/testing/selftests/lkdtm/config`. 

The problem has been caught by manually running the `merge_config.sh` tool. At the moment, `./kci_build make_config` isn't emitting this kind of warning. It should have emitted the same warnings as it also uses the`merge_config.sh` tool to merge the config.

Solution: 
All config fragments should list all dependent config options. For now, I'm facing issues with selftest/.../config files (`selftest/lkdtm/config in particular). They should be fixed in the kernel to include the dependent config options.

**Comment by musamaanjum** [comment]
Sent two patches to update `tools/testing/selftest/lkdtm/config`:
https://lore.kernel.org/lkml/20220111143614.629452-1-usama.anjum@collabora.com/
https://lore.kernel.org/lkml/20220111143614.629452-2-usama.anjum@collabora.com/

**Comment by musamaanjum** [comment]
Sent V2 after adding fixes tag:
https://lore.kernel.org/lkml/20220121145154.1795447-1-usama.anjum@collabora.com/
https://lore.kernel.org/lkml/20220121145154.1795447-2-usama.anjum@collabora.com/

**Comment by gctucker** [comment]
> Sent V2 after adding fixes tag: https://lore.kernel.org/lkml/20220121145154.1795447-1-usama.anjum@collabora.com/ https://lore.kernel.org/lkml/20220121145154.1795447-2-usama.anjum@collabora.com/

These 2 patches are now being applied to the `staging-next` branch.

**Comment by musamaanjum** [comment]
These patches have been accepted. I've confirmed their presence in linux-next.  The sub-test of LKDTM, array bounds which were dependent on this patch is passing now on next: https://storage.staging.kernelci.org/kernelci/staging-next/staging-next-20220204.0/x86_64/x86_64_defconfig+x86-chromebook+kselftest/gcc-10/lab-collabora/kselftest-lkdtm-hp-11A-G6-EE-grunt.html
