### ISSUE TITLE
kselftest Makefiles don't support separate output directory build

### ISSUE THREAD

**Issue by musamaanjum** [kernelci/kernelci-project#85]
Kselftest Makefiles have hard-coded paths. Out of tree build of kselftest fails of some tests if they depend on latest uapi in tree headers. 

To reproduce:
Run `make -C tools/testing/selftests/ O=<build_dir>` inside kernel top most directory. The build of some tests will get fail in this way. 

Workaround:
Either build kselftests in tree in same directory or build kselftest from the build directory with slightly changed command, `make -C source/tools/testing/selftests`.

**Comment by musamaanjum** [comment]
Patch series has been sent: https://lore.kernel.org/lkml/20220118112909.1885705-1-usama.anjum@collabora.com/T/#mf68787ae303e49314db5a5053832e915c71b512d

**Comment by musamaanjum** [comment]
2 un-related patches were also sent while working on this:
https://lore.kernel.org/lkml/20220118122053.1941915-1-usama.anjum@collabora.com/
https://lore.kernel.org/lkml/20220119103332.2887370-1-usama.anjum@collabora.com/

**Comment by gctucker** [comment]
OK thanks, all your patches are now added to the `staging-next` branch:
https://github.com/kernelci/linux/commits/staging-next

**Comment by musamaanjum** [comment]
The patch series has been accepted. This also fixes https://github.com/kernelci/kernelci-core/issues/981.

**Comment by gctucker** [comment]
I'd like to see the build issues disappear at least with linux-next in the KernelCI results before closing this issue.  That's the difference between the "Fixed" and "Verified" status.

**Comment by musamaanjum** [comment]
The support of separate directory was added and build of intended kselftests (futex, kvm, net, mptcp, kvm, vm etc) has been fixed on the linux-next. Here are logs: https://storage.staging.kernelci.org/next/master/next-20220128/x86_64/x86_64_defconfig+x86-chromebook+kselftest/gcc-10/logs/kselftest.log

There are a few more build failures because of some unrelated other errors. Separate tickets for those:
https://github.com/kernelci/kernelci-core/issues/1013
https://github.com/kernelci/kernelci-project/issues/95

**Comment by gctucker** [comment]
This could be the basis for a nice blog post, to explain how KernelCI highlighted some kernel issues and how they got fixed and then eventually verified with KernelCI results. If you don't have the time then I could make a Tweet about it at least.

**Comment by gctucker** [comment]
> If you don't have the time then I could make a Tweet about it at least.

Or you may make one and the KernelCI account will retweet it... Let me know if you want to do any of that.

**Comment by musamaanjum** [comment]
@gctucker It would be interesting. Let's do it. I'll write something and share it with you.
