### ISSUE TITLE
`alarm_alm_set_minute` from `rtc-kselftest` times out on `rk3399-gru-kevin`

### ISSUE THREAD

**Issue by nfraprado** [kernelci/kernelci-project#86]
While adding the `rtc-kselftest` test to `rk3399-gru-kevin` in https://github.com/kernelci/kernelci-core/pull/980, it was noticed that the `alarm_alm_set_minute` test case fails with a timeout:
```
# #  RUN           rtc.alarm_alm_set_minute ...
# # rtctest.c:238:alarm_alm_set_minute:Alarm time now set to 15:53:00.
# # rtctest.c:250:alarm_alm_set_minute:Expected 0 (0) != rc (0)
# # alarm_alm_set_minute: Test terminated by assertion
# #          FAIL  rtc.alarm_alm_set_minute
# not ok 6 rtc.alarm_alm_set_minute
```

 This is most likely a bug in the RTC driver used for that device, `rtc-cros-ec`.

Lava run: https://lava.collabora.co.uk/scheduler/job/5415176

**Comment by padovan** [comment]
Old issue. (also we are not tracking kernel test failure/issues through GitHub anymore)
