### ISSUE TITLE
Build of kselftests fails if separate output directory is specified as relative path through kernel's top most Makefile

### ISSUE THREAD

**Issue by musamaanjum** [kernelci/kernelci-project#92]
Kernel's build works fine if a relative or absolute path is specified as output directories:
```
make O=build
make O=/opt/build
```
It may be the subconscious demand of developers that kselftest build should also work the same way. Build of kselftests works fine when output directory's path is absolute:
```
make kselftest O=/opt/build
```
But build of kselftest fails if a path is specified which is the sub directory of the topmost Makefile:
```
make kselftest O=build V=1 or make kselftest O=/abcd/build V=1
make -C /home/usama/repos/kernel/linux_mainline2/build -f /home/usama/repos/kernel/linux_mainline2/Makefile kselftest
make[1]: Entering directory '/home/usama/repos/kernel/linux_mainline2/build'
make -C ../tools/testing/selftests run_tests
make --no-builtin-rules INSTALL_HDR_PATH=$BUILD/usr \
	ARCH=x86 -C ../../.. headers_install
make[3]: Entering directory '/home/usama/repos/kernel/linux_mainline2'
Makefile:1080: ../scripts/Makefile.extrawarn: No such file or directory
make[3]: *** No rule to make target '../scripts/Makefile.extrawarn'.  Stop.
make[3]: Leaving directory '/home/usama/repos/kernel/linux_mainline2'
make[2]: *** [Makefile:158: khdr] Error 2
make[1]: *** [/home/usama/repos/kernel/linux_mainline2/Makefile:1417: kselftest] Error 2
make[1]: Leaving directory '/home/usama/repos/kernel/linux_mainline2/build'
make: *** [Makefile:226: __sub-make] Error 2
```

**Comment by musamaanjum** [comment]
Patch has been sent: https://lore.kernel.org/lkml/20220223191016.1658728-1-usama.anjum@collabora.com/

**Comment by musamaanjum** [comment]
So this particular build error only appears when the build directory is a subdirectory in the kernel's top most source tree. 
When `make kselftest-all O=$mainline/build3 V=1` is executed, makefile executes following commands in order:
1. Output directory is being changed to build3 in this command and then `make -C` is called from there.
```
make -C /home/usama/repos/kernel/linux_mainline/build3 -f /home/usama/repos/kernel/linux_mainline/Makefile kselftest-all
$abs_srctree iss [/home/usama/repos/kernel/linux_mainline]
$abs_objtree iss [/home/usama/repos/kernel/linux_mainline/build3]
$srctree iss [..]
$PWD iss [/home/usama/repos/kernel/linux_mainline/build3]
```
2. Note that `srctree` is set to `..` as `build3` is a subdirectory of the topmost kernel source. This path is correct at this point. But it'll create problems when selftests/Makefile will call `make install headers_install`.
```
make -C ../tools/testing/selftests all
```
3. 
`make --no-builtin-rules INSTALL_HDR_PATH=/home/usama/repos/kernel/linux_mainline/build3/usr	ARCH=x86 -C ../../.. headers_install`
4. Here `srctree` should have been `.` or absolute path instead of `..`.
```
make[3]: Entering directory '/home/usama/repos/kernel/linux_mainline'
$abs_srctree iss [/home/usama/repos/kernel/linux_mainline]
$abs_objtree iss [/home/usama/repos/kernel/linux_mainline/build3]
$srctree iss [..]
$PWD iss [/home/usama/repos/kernel/linux_mainline]
Makefile:1107: ../scripts/Makefile.extrawarn: No such file or directory
```

From [Makefile](https://elixir.bootlin.com/linux/latest/source/Makefile):
```
ifeq ($(abs_srctree),$(abs_objtree))
        # building in the source tree
        srctree := .
	building_out_of_srctree :=
else
        ifeq ($(abs_srctree)/,$(dir $(abs_objtree)))
                # building in a subdirectory of the source tree
                srctree := ..
        else
                srctree := $(abs_srctree)
        endif
	building_out_of_srctree := 1
endif
```
`ifeq ($(abs_srctree)/,$(dir $(abs_objtree)))` condition is setting `srctree` to `..`. This is wrong. This condition isn't considering that `header_install` doesn't depend on `abs_srctree and abs_objtree`. This condition needs to be tweaked or removed for the `install_headers` to work fine and fix this issue. In my first version fix, I've added `KBUILD_ABS_SRCTREE=1` to the kselftest target which sets the `srctree` to abs_srctree forcefully affecting only kselftest targets. This seems the cleanest fix. Alternatively we should remove this condition `ifeq ($(abs_srctree)/,$(dir $(abs_objtree)))` but it'll affect other targets as well.

**Comment by musamaanjum** [comment]
I was unable to fix this bug. I've reported this bug: https://lore.kernel.org/lkml/c25d7ea7-4f72-4a2b-d8c3-d317e64fcbbb@collabora.com/

**Comment by musamaanjum** [comment]
I've added the condition that the srctree isn't set to .. in case of install_headers target. But this Makefile is called several times. Once srctree is set in the first invocation, it isn't being updated.

```diff
diff --git a/Makefile b/Makefile
index 35f08adbadd8..6e69430902aa 100644
--- a/Makefile
+++ b/Makefile
@@ -235,21 +235,22 @@ ifeq ($(need-sub-make),)
 # but we want to display it when entering to the output directory
 # so that IDEs/editors are able to understand relative filenames.
 MAKEFLAGS += --no-print-directory
-
+$(info $$srctree iss [${srctree}])
 ifeq ($(abs_srctree),$(abs_objtree))
         # building in the source tree
         srctree := .
        building_out_of_srctree :=
 else
-        ifeq ($(abs_srctree)/,$(dir $(abs_objtree)))
-                # building in a subdirectory of the source tree
-                srctree := ..
-        else
-                srctree := $(abs_srctree)
-        endif
-       building_out_of_srctree := 1
+        srctree := $(abs_srctree)
+        building_out_of_srctree := 1
+ifneq ($(MAKECMDGOALS),install_headers)
+       ifeq ($(abs_srctree)/,$(dir $(abs_objtree)))
+               # building in a subdirectory of the source tree
+               srctree := ..
+       endif
 endif
-
+endif
+$(info $$srctree iss [${srctree}])
 ifneq ($(KBUILD_ABS_SRCTREE),)
 srctree := $(abs_srctree)
 endif
```
```bash
make kselftest O=build V=1 
make -C /home/usama/repos/kernel/linux_mainline/build -f /home/usama/repos/kernel/linux_mainline/Makefile kselftest
make[1]: Entering directory '/home/usama/repos/kernel/linux_mainline/build'
$srctree iss []
$srctree iss [..]
make -C ../tools/testing/selftests run_tests
make --no-builtin-rules INSTALL_HDR_PATH=/home/usama/repos/kernel/linux_mainline/build/usr \
	ARCH=x86 -C ../../.. headers_install
make[3]: Entering directory '/home/usama/repos/kernel/linux_mainline'
$srctree iss [..]
$srctree iss [..]
Makefile:1104: ../scripts/Makefile.extrawarn: No such file or directory
```

**Comment by musamaanjum** [comment]
Reported bug thread: https://lore.kernel.org/lkml/a9470bfc-bddc-6aa6-0043-d49eb57611fe@linuxfoundation.org/ Mashiro has said that we can merge the workaround if nobody finds the main issue. Shuah has asked if I can fix the bug. I haven't found any solution other than the one I sent which was regarded as work around. 

@gctucker have a look at this bug if you can make something out of it.

**Comment by gctucker** [comment]
From one of your emails in the thread:

> Yeah, I've tried to test all the ways. Here are the different ways I've
> used to test it:
> 1) Same directory build of kselftest (this is already working)
> make kselftest
> make kselftest-all
> make kselftest-install
> make kselftest-clean
> make kselftest-gen_tar
> 
> 2) These were failing when separate output directory is specified either
> as relative or absolute path. After adding this patch, these are also
> working. kselfetst.rst mentions separate output directory build in this way.
> make kselftest O=build
> make kselftest-all O=build
> make kselftest-install O=build
> make kselftest-clean O=build
> make kselftest-gen_tar O=build
> 
> make kselftest O=/build
> make kselftest-all O=/build
> make kselftest-install O=/build
> make kselftest-clean O=/build
> make kselftest-gen_tar O=/build
> 
> Tested on top of next-20220307 after applying this patch.

It would seem useful to enable all these build combination for the kselftest tree in KernelCI.

**Comment by musamaanjum** [comment]
I've found a fix by bisection and looking at the culprit commit. Let's see. https://lore.kernel.org/lkml/20220627070214.432390-1-usama.anjum@collabora.com/

**Comment by gctucker** [comment]
Also just to be clear, the issue is only with `headers_install` being called from the kselftest Makefile. If you do this, as an experiment:
```diff
diff --git a/Makefile b/Makefile
index 1a6678d817bd..cb31c29ebd29 100644
--- a/Makefile
+++ b/Makefile
@@ -1350,7 +1350,7 @@ PHONY += kselftest
 kselftest:
        $(Q)$(MAKE) -C $(srctree)/tools/testing/selftests run_tests
 
-kselftest-%: FORCE
+kselftest-%: headers_install FORCE
        $(Q)$(MAKE) -C $(srctree)/tools/testing/selftests $*
 
 PHONY += kselftest-merge
diff --git a/tools/testing/selftests/Makefile b/tools/testing/selftests/Makefile
index de11992dc577..6c32ce6c6189 100644
--- a/tools/testing/selftests/Makefile
+++ b/tools/testing/selftests/Makefile
@@ -174,7 +174,7 @@ else
                ARCH=$(ARCH) -C $(top_srcdir) headers_install
 endif
 
-all: khdr
+all:
        @ret=1;                                                 \
        for TARGET in $(TARGETS); do                            \
                BUILD_TARGET=$$BUILD/$$TARGET;                  \
```
then things like `make O=build kselftest-all` just work. But then of course it doesn't work anymore with `-C tools/testing/selftests`. Just to say, the issue is really in the `khdr` make target because `$(top_srcdir)` points to the root directory of the source tree and then `$(srctree)` is `..` because the parent make was called from the `build` sub-directory.

**Comment by gctucker** [comment]
Another way to look at it is to make an implicit requirement that headers need to be installed and the users could do `make install_headers` manually before building kselftest, but that's not great either. In a way it kind of makes sense as the kselftest build is really separate from the kernel build so installing headers is like an external dependency, but in practice they are a bit more intertwined than that and people probably expect the headers to still be installed automatically when just doing a kselftest build. Just another thought I had while looking into this.

Also there doesn't seem to be any other case in the whole kernel tree where a Makefile in a sub-directory tries to call a make target defined in the top-level Makefile. So it's also possible that we can improve the way this is done with the proposed fix in your last comment. But let's see what Masahiro-san thinks of it.

**Comment by musamaanjum** [comment]
@gctucker V2 got rejected.

**Comment by gctucker** [comment]
I see: https://lore.kernel.org/lkml/CAK7LNARxG2A9us1V7Z+Fjhuu8mJ7kAw6CNH56E+nYymeCvyqSg@mail.gmail.com/

**Comment by gctucker** [comment]
I've sent a series that removes `khdr` from the kselftest Makefile and add `headers_install` as a dependency from the top-level Makefile. This fixes the issue with `make O=build kselftest-all`. The only drawback is that now `make headers_install` needs to be run before `make -C tools/testing/selftests` which is arguably a valid requirement in this case (waiting for the maintainers' feedback to confirm this assumption).

**Comment by gctucker** [comment]
Email thread: https://lore.kernel.org/lkml/cover.1657296695.git.guillaume.tucker@collabora.com/

**Comment by gctucker** [comment]
The patches have been applied to the `kselftest/next` branch. A couple of minor fixes have been sent too:

* [Makefile: replace headers_install with headers for kselftest](https://lore.kernel.org/lkml/a7af58feaa6ae6d3b0c8c55972a470cec62341e5.1657693952.git.guillaume.tucker@collabora.com/)
* [selftests/landlock: drop deprecated headers dependency](https://lore.kernel.org/lkml/b79c51ed97219b1c10e2e3f2bcd3269305f0f035.1657694067.git.guillaume.tucker@collabora.com/)
