### ISSUE TITLE
Fix warning in kselftest/futex Makefile when more than one build job is used (-j 12)

### ISSUE THREAD

**Issue by musamaanjum** [kernelci/kernelci-project#94]
```
make[1]: Entering directory '/home/usama/repos/kernel/linux_mainline/tools/testing/selftests/futex'
make[2]: Entering directory '/home/usama/repos/kernel/linux_mainline/tools/testing/selftests/futex'
make[2]: warning: jobserver unavailable: using -j1. Add '+' to parent make rule.
````
Found by KernelCI: https://storage.kernelci.org/renesas/master/renesas-devel-2022-01-11-v5.16/x86_64/x86_64_defconfig+x86-chromebook+kselftest/gcc-10/logs/kselftest.log

**Comment by gctucker** [comment]
Same comment as the other issue, was this detected by KernelCI?  If it's in a KernelCI build log then that's good enough.

**Comment by musamaanjum** [comment]
Patch has been sent: Patch has been sent: https://lore.kernel.org/lkml/20220127174447.754605-1-usama.anjum@collabora.com/

**Comment by gctucker** [comment]
@musamaanjum You may also add this trailer in your patch(es) if you found the issue thanks to KernelCI:
```
Reported-by: "kernelci.org bot" <bot@kernelci.org>
```

**Comment by musamaanjum** [comment]
The patch was accepted. Waiting for the patch to reach the linux-next.

**Comment by musamaanjum** [comment]
Patch has been accepted and results can be viewed here: https://storage.staging.kernelci.org/kernelci/staging-next/staging-next-20220204.0/x86_64/x86_64_defconfig+x86-chromebook+kselftest/clang-14/logs/kselftest.log The build warning of this test has been fixed.
